### ISSUE TITLE
Advanced Stats 2.2.0.0 RC1

### ISSUE THREAD

**Issue by TyKonKet** [Royal-Modding/FS19_AdvancedStats#7]
Hi @shane101978, following your request #4, we've added support to display statistics with American measure units.
A new RC version have been released, and if you want, you can [give it a try](https://github.com/Royal-Modding/FS19_AdvancedStats/releases/tag/2.2.0.0-RC1) just now.
Please let us know your impressions as soon as you will try it.

**Comment by shane101978** [comment]
Thanks for taking the time for this, from what I see the only thing that is needing adjustment is maybe changing from gallons to bushels and tons on certain equipment, for example the combine would show bushels threshed instead of gallons and the forage wagon would be tons instead of gallons.  Once again thanks for taking time to work on this.

**Comment by TyKonKet** [comment]
@shane101978 currently I'm not able to use different measure units for things like fuel, grains, liquids and so on since they were all meant for the International System of Units where volume is expressed in liters, but with a bit of rework I can make it work.
Unluckily I can't do the same with tons, since they are a weight measure unit and in Farming Simulator everything is measured in volume (there's no way to "directly" convert volume to weight).

**Comment by TyKonKet** [comment]
@shane101978 one more question, I'm not very familiar with American units of measure, should I only use Gallons to measure fuel? or are there other things that are measured in gallons?

**Comment by shane101978** [comment]
That would be correct, anything that is a liquid is measured in gallons and bulk materials are measured in either bushels or tons....fuel, milk, water, ect would all be measured in gallons, fertilizer and lime would be measured in tons and grain (corn, soybeans, wheat, seed for planting) would be measured in bushels.  The only exception that I can think of would be liquid fertilizer is measured in gallons and granular or dry fertilizer is measured in either pounds or tons depending on how it is purchased.

**Comment by TyKonKet** [comment]
Hi @shane101978, I've improved it with 8186c7e3e86e31024c4eac3d93a4b27d76066ded, I know it's still not perfect, but that's the best I can do at the moment.
You can download the [latest RC version here](https://github.com/Royal-Modding/FS19_AdvancedStats/releases/tag/2.2.0.0-RC3).

**Comment by shane101978** [comment]
This is pretty good as to what I was looking for, THANKS!!  One other question, is there a way to reset the statistics say between fields but keep the machine and implement totals or would it need to be a total reset.  Thanks again!
    On Thursday, March 18, 2021, 09:09:41 AM EDT, Matteo Autieri ***@***.***> wrote:  
 
 


Hi @shane101978, I've improved it with 8186c7e, I know it's still not perfect, but that's the best I can do at the moment.
You can download the latest RC version here.

**Comment by TyKonKet** [comment]
@shane101978
Actually the mod already have two "layers" of statistics.
There are:
 - Normal stats
 - Partial stats (which can be reset at your needs)

When you press ALT + T for the first time "normal stats" are displayed, if you press it again, "partial stats" are displeyed, press ALT + T once again to hide stats display and so on, the loop restarts.

When "partial stats" are displayed you can also press CTRL + T to reset them.

**Comment by shane101978** [comment]
Thanks, I guess I didn't realize that.

    On Thursday, March 18, 2021, 01:21:02 PM EDT, Matteo Autieri ***@***.***> wrote:  
 
 


@shane101978
Actually the mod already have two "layers" of statistics.
There are:
   
   - Normal stats
   - Partial stats (which can be reset at your needs)

When you press ALT + T for the first time "normal stats" are displayed, if you press it again, "partial stats" are displeyed, press ALT + T once again to hide stats display and so on, the loop restarts.

When "partial stats" are displayed you can also press CTRL + T to reset them.
